# Generated by Django 5.2.11 on 2026-02-11 16:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Is this category active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Category',
                'verbose_name_plural': 'Gallery Categories',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(blank=True, help_text='Organization mission statement')),
                ('vision', models.TextField(blank=True, help_text='Organization vision statement')),
                ('values', models.TextField(blank=True, help_text='Core values (one per line)')),
                ('history', models.TextField(blank=True, help_text='Organization history')),
                ('hero_title', models.CharField(default='Serving Humanity with Compassion', help_text='Homepage hero section title', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, help_text='Homepage hero section subtitle', max_length=300)),
                ('hero_image', models.ImageField(blank=True, help_text='Homepage hero background image', null=True, upload_to='site/')),
                ('total_beneficiaries', models.PositiveIntegerField(default=0, help_text='Total people helped')),
                ('active_programs', models.PositiveIntegerField(default=0, help_text='Number of active programs')),
                ('volunteers_count', models.PositiveIntegerField(default=0, help_text='Number of volunteers')),
                ('years_of_service', models.PositiveIntegerField(default=1, help_text='Years in operation')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn page URL')),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number with country code', max_length=20)),
                ('footer_text', models.TextField(blank=True, help_text='Footer description text')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Person's name", max_length=200)),
                ('role', models.CharField(blank=True, help_text='Role or designation (e.g., Beneficiary, Volunteer)', max_length=100)),
                ('photo', models.ImageField(blank=True, help_text="Person's photo (optional)", null=True, upload_to='testimonials/')),
                ('testimonial', models.TextField(help_text='Testimonial text')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='Rating out of 5')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage?')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Sender's full name", max_length=200)),
                ('email', models.EmailField(help_text="Sender's email address", max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, help_text="Sender's phone number (optional)", max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('donation', 'Donation Related'), ('volunteer', 'Volunteer Inquiry'), ('partnership', 'Partnership Proposal'), ('complaint', 'Complaint/Feedback'), ('other', 'Other')], default='general', help_text='Message subject category', max_length=30)),
                ('message', models.TextField(help_text='Message content')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('resolved', 'Resolved')], default='new', help_text='Submission status', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to sender)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Sender's IP address", null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent', max_length=300)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='core_contac_status_a7d73c_idx')],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Image title', max_length=200)),
                ('image', models.ImageField(help_text='Gallery image (recommended: 1200x800px)', upload_to='gallery/%Y/%m/')),
                ('description', models.TextField(blank=True, help_text='Image description or story')),
                ('event_date', models.DateField(blank=True, help_text='Date when photo was taken', null=True)),
                ('location', models.CharField(blank=True, help_text='Photo location', max_length=200)),
                ('photographer', models.CharField(blank=True, help_text='Photographer name', max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage?')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(help_text='Image category', on_delete=django.db.models.deletion.PROTECT, related_name='images', to='core.gallerycategory')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-is_featured', '-uploaded_at'],
            },
        ),
    ]
