# Generated by Django 5.2.11 on 2026-02-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, help_text='About page main text'),
        ),
    ]
