# Generated by Django 5.2.11 on 2026-02-12 07:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Position title (e.g., President, General Secretary)', max_length=100, unique=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Display order (lower number = higher priority)')),
                ('description', models.TextField(blank=True, help_text='Brief description of the role')),
                ('is_active', models.BooleanField(default=True, help_text='Is this position currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Management Post',
                'verbose_name_plural': 'Management Posts',
                'ordering': ['priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OfficeBearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the office bearer', max_length=200)),
                ('photo', models.ImageField(blank=True, help_text='Professional photo (recommended: 400x400px)', null=True, upload_to='leadership/photos/%Y/')),
                ('status', models.CharField(choices=[('current', 'Current'), ('former', 'Former')], default='current', help_text='Current or Former', max_length=10)),
                ('term_start', models.DateField(help_text='Start date of the term')),
                ('term_end', models.DateField(blank=True, help_text='End date of the term (leave empty if current)', null=True)),
                ('email', models.EmailField(blank=True, help_text='Official email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('bio', models.TextField(blank=True, help_text='Brief biography or achievements')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL slug', max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(help_text='Leadership position', on_delete=django.db.models.deletion.PROTECT, related_name='office_bearers', to='leadership.managementpost')),
            ],
            options={
                'verbose_name': 'Office Bearer',
                'verbose_name_plural': 'Office Bearers',
                'ordering': ['-status', 'post__priority', '-term_start'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('appointment', 'Appointment'), ('resignation', 'Resignation'), ('election', 'Election'), ('transition', 'Transition'), ('milestone', 'Milestone')], help_text='Type of event', max_length=20)),
                ('event_date', models.DateField(help_text='Date of the event')),
                ('description', models.TextField(help_text='Details about the event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office_bearer', models.ForeignKey(help_text='Related office bearer', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leadership.officebearer')),
            ],
            options={
                'verbose_name': 'Leadership History',
                'verbose_name_plural': 'Leadership Histories',
                'ordering': ['-event_date'],
            },
        ),
        migrations.AddIndex(
            model_name='officebearer',
            index=models.Index(fields=['status', 'post'], name='leadership__status_150be0_idx'),
        ),
        migrations.AddIndex(
            model_name='officebearer',
            index=models.Index(fields=['term_start', 'term_end'], name='leadership__term_st_88d10e_idx'),
        ),
    ]
