# Generated by Django 5.2.11 on 2026-03-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officebearer',
            name='photo',
            field=models.ImageField(blank=True, help_text='Professional photo (recommended: 400x400px)', null=True, upload_to='images/'),
        ),
    ]
