# Generated by Django 5.2.11 on 2026-02-12 07:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Education, Health, Emergency Relief)', max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class name (e.g., fa-graduation-cap for Font Awesome)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for UI display (e.g., #007bff)', max_length=7)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Display order (lower number = higher priority)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this category active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Category',
                'verbose_name_plural': 'Program Categories',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WelfareProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Program title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL slug', max_length=200, unique=True)),
                ('short_description', models.CharField(help_text='Brief summary (shown in listings)', max_length=300)),
                ('detailed_description', models.TextField(help_text='Detailed program description')),
                ('objectives', models.TextField(blank=True, help_text='Program objectives and goals')),
                ('featured_image', models.ImageField(blank=True, help_text='Main program image (recommended: 1200x600px)', null=True, upload_to='programs/featured/%Y/')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='planning', help_text='Current program status', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Program start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Program end date (if applicable)', null=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated budget in PKR', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Actual cost incurred in PKR', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_beneficiaries', models.PositiveIntegerField(blank=True, help_text='Estimated number of beneficiaries', null=True)),
                ('actual_beneficiaries', models.PositiveIntegerField(blank=True, help_text='Actual number of people helped', null=True)),
                ('location', models.CharField(blank=True, help_text='Program location (e.g., Sonikot, Gilgit)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Show this program on website?')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this program on homepage?')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Program category', on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='programs.programcategory')),
            ],
            options={
                'verbose_name': 'Welfare Program',
                'verbose_name_plural': 'Welfare Programs',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Update title', max_length=200)),
                ('description', models.TextField(help_text='Update details')),
                ('image', models.ImageField(blank=True, help_text='Update image (optional)', null=True, upload_to='programs/updates/%Y/')),
                ('update_date', models.DateField(help_text='Date of this update')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(help_text='Related program', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='programs.welfareprogram')),
            ],
            options={
                'verbose_name': 'Program Update',
                'verbose_name_plural': 'Program Updates',
                'ordering': ['-update_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgramImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Program image', upload_to='programs/gallery/%Y/')),
                ('caption', models.CharField(blank=True, help_text='Image caption or description', max_length=200)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(help_text='Related program', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='programs.welfareprogram')),
            ],
            options={
                'verbose_name': 'Program Image',
                'verbose_name_plural': 'Program Images',
                'ordering': ['priority', '-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='welfareprogram',
            index=models.Index(fields=['status', 'is_active'], name='programs_we_status_ae3b13_idx'),
        ),
        migrations.AddIndex(
            model_name='welfareprogram',
            index=models.Index(fields=['-created_at'], name='programs_we_created_7df149_idx'),
        ),
    ]
