# Generated by Django 5.2.11 on 2026-03-09 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programupdate',
            name='program',
        ),
        migrations.RemoveField(
            model_name='welfareprogram',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='programcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Program Categories'},
        ),
        migrations.RemoveField(
            model_name='programcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='programcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='programcategory',
            name='priority',
        ),
        migrations.AddField(
            model_name='programcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='programcategory',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Gray'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Cyan')], default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='programcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('target_beneficiaries', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='programs.programcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProgramImage',
        ),
        migrations.DeleteModel(
            name='ProgramUpdate',
        ),
        migrations.DeleteModel(
            name='WelfareProgram',
        ),
    ]
